# Generated by Django 4.2.3 on 2023-07-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_medicament_order_specialization_visit_orderdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='medicament',
        ),
    ]
