# Generated by Django 4.2.3 on 2023-07-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_order_medicament'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorSpecialization',
        ),
    ]
