# Generated by Django 4.2.3 on 2023-07-12 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_delete_doctorspecialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='doctor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
