# Generated by Django 4.2.3 on 2023-07-12 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_specialization_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='doctor',
            field=models.ManyToManyField(related_name='doctors', to=settings.AUTH_USER_MODEL),
        ),
    ]
